### ISSUE TITLE
Makefile enthält nicht vorhandenes Sourcefile

### ISSUE THREAD

**Issue by terraformer** [kfkonrad/hsklclasses#4]
Makefile enthält nicht vorhandenes Sourcefile: Anleitung_Celoplan.tex
(Zeile 1: SOURCEFILE=Anleitung_Celoplan)

**Comment by kfkonrad** [comment]
Ja, das ist einfach eins meiner (älteren) Makefiles, das ich einfach hier reinkopiert habe. Die Variable SOURCEFILE muss an den Namen der Haupt-.tex-Datei angepasst werden. Das werde ich im Readme erwähnen.
