### ISSUE TITLE
Fehlender Optionsparameter für inputenc [utf8] ?

### ISSUE THREAD

**Issue by terraformer** [kfkonrad/hsklclasses#5]
...
(/usr/share/texmf-dist/tex/generic/hyph-utf8/loadhyph/loadhyph-de-1996.tex
UTF-8 German hyphenation patterns (reformed orthography)
(/usr/share/texmf-dist/tex/generic/hyph-utf8/patterns/tex/hyph-de-1996.tex
German Hyphenation Patterns (Reformed Orthography, 2006) `dehyphn-x' 2017-03-31
 (WL)))))) (/usr/share/texmf-dist/tex/latex/base/inputenc.sty

! Package inputenc Error: inputenc is not designed for xetex or luatex.
(inputenc)                only UTF-8 supported.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.158 \endinput
             
? H
For xelatex or lualatex save the document in UTF-8 encoding
and do not use inputenc, or use the [utf8] option.
?

**Comment by kfkonrad** [comment]
inputenc is not designed for xetex or luatex.
Da steht doch was der Fehler ist. Die Enginge muss `pdflatex` lauten. Im Makefile also `THELATEX=pdflatex` eintragen, falls das benutzt wurde. Alternativ das Kommando in der Konsole entsprechend anpassen.

In welcher Datei tritt das überhaupt auf?

**Comment by terraformer** [comment]
Beim Versuch "Bachelorarbeit" (Das Beispiel) mit dem Makefile aus dem Hauptverzeichnis nach Anleitung zu erstellen. "THELATEX=pdflatex" in Zeile 3 des Makefiles löst das Problem tatsächlich.
